"""Controlled vocabularies: topics/themes, biblical people, places, events (with passages),
life situations and questions. Used by P-06 (as supplied vocab), by the deterministic
fallback tagger, by contextual passage detection (named stories) and by the Scripture Map.
"""
from __future__ import annotations

# (slug, name, category, aliases/keywords)
TOPICS: list[tuple[str, str, str, list[str]]] = [
    ("faith", "Faith", "christian_life", ["faith", "believe", "believing", "trust god"]),
    ("hope", "Hope", "christian_life", ["hope", "hopeful", "hoping"]),
    ("love", "Love", "virtue", ["love one another", "loving", "god's love", "love of god"]),
    ("grace", "Grace", "theology", ["grace", "undeserved favor", "unmerited favor"]),
    ("mercy", "Mercy", "theology", ["mercy", "merciful", "compassion of god"]),
    ("forgiveness", "Forgiveness", "christian_life", ["forgive", "forgiveness", "forgiving", "forgave", "forgiven"]),
    ("salvation", "Salvation", "theology", ["salvation", "saved", "save us", "savior", "saviour"]),
    ("redemption", "Redemption", "theology", ["redemption", "redeem", "redeemed", "ransom"]),
    ("repentance", "Repentance", "christian_life", ["repent", "repentance", "turn from sin"]),
    ("sin", "Sin", "theology", ["sin", "sins", "sinful", "transgression"]),
    ("prayer", "Prayer", "practice", ["pray", "prayer", "praying", "prayed"]),
    ("worship", "Worship", "practice", ["worship", "praise", "adore"]),
    ("thanksgiving", "Thanksgiving & Gratitude", "practice", ["thankful", "gratitude", "grateful", "give thanks", "thanksgiving"]),
    ("suffering", "Suffering", "struggle", ["suffering", "suffer", "pain", "hardship", "affliction", "trials", "trial"]),
    ("perseverance", "Perseverance", "christian_life", ["perseverance", "persevere", "endurance", "endure", "steadfast"]),
    ("trust", "Trust in God", "christian_life", ["trust", "trusting", "rely on god", "depend on god"]),
    ("providence", "Providence & Sovereignty", "theology", ["providence", "sovereign", "sovereignty", "in control", "god's plan", "works together for good"]),
    ("peace", "Peace", "christian_life", ["peace", "peaceful", "calm"]),
    ("anxiety", "Anxiety & Worry", "struggle", ["anxiety", "anxious", "worry", "worried", "worrying"]),
    ("fear", "Fear & Courage", "struggle", ["fear", "afraid", "courage", "courageous", "do not be afraid"]),
    ("joy", "Joy", "christian_life", ["joy", "joyful", "rejoice"]),
    ("wisdom", "Wisdom", "virtue", ["wisdom", "wise", "understanding", "discernment"]),
    ("humility", "Humility", "virtue", ["humility", "humble", "pride", "proud"]),
    ("obedience", "Obedience", "christian_life", ["obey", "obedience", "obedient", "commandments"]),
    ("holiness", "Holiness", "christian_life", ["holy", "holiness", "sanctification", "sanctified"]),
    ("justice", "Justice & Righteousness", "virtue", ["justice", "righteousness", "righteous", "do justly", "oppressed"]),
    ("compassion", "Compassion & Kindness", "virtue", ["compassion", "kindness", "kind", "tenderhearted"]),
    ("generosity", "Generosity & Stewardship", "christian_life", ["generous", "generosity", "giving", "tithe", "stewardship"]),
    ("money", "Money & Contentment", "christian_life", ["money", "wealth", "riches", "contentment", "content"]),
    ("work", "Work & Calling", "christian_life", ["work", "calling", "vocation", "purpose"]),
    ("rest", "Rest & Sabbath", "practice", ["rest", "sabbath", "weary", "burdened"]),
    ("family", "Family & Parenting", "relationship", ["family", "parent", "parents", "children", "father", "mother"]),
    ("marriage", "Marriage", "relationship", ["marriage", "husband", "wife", "married"]),
    ("friendship", "Friendship", "relationship", ["friend", "friends", "friendship"]),
    ("church", "Church & Community", "relationship", ["church", "community", "fellowship", "body of christ", "one another"]),
    ("unity", "Unity", "relationship", ["unity", "united", "one body"]),
    ("discipleship", "Discipleship", "mission", ["disciple", "discipleship", "follow jesus", "follow me"]),
    ("evangelism", "Evangelism & Mission", "mission", ["gospel", "evangelism", "witness", "make disciples", "great commission", "mission"]),
    ("holy-spirit", "The Holy Spirit", "theology", ["holy spirit", "the spirit", "comforter", "helper"]),
    ("creation", "Creation", "theology", ["creation", "created", "creator"]),
    ("covenant", "Covenant & Promises", "theology", ["covenant", "promise", "promises"]),
    ("kingdom", "Kingdom of God", "theology", ["kingdom of god", "kingdom of heaven"]),
    ("eternal-life", "Eternal Life & Heaven", "eschatology", ["eternal life", "heaven", "everlasting life"]),
    ("resurrection", "Resurrection", "theology", ["resurrection", "risen", "raised from the dead", "rose again"]),
    ("cross", "The Cross & Atonement", "theology", ["cross", "crucified", "atonement", "sacrifice for sin"]),
    ("identity", "Identity in Christ", "christian_life", ["identity", "new creation", "child of god", "children of god", "adopted"]),
    ("temptation", "Temptation", "struggle", ["temptation", "tempted", "tempt"]),
    ("spiritual-warfare", "Spiritual Warfare", "christian_life", ["spiritual warfare", "armor of god", "the devil", "enemy"]),
    ("healing", "Healing", "christian_life", ["healing", "heal", "healed", "sickness", "illness"]),
    ("grief", "Grief & Loss", "struggle", ["grief", "grieve", "grieving", "mourning", "loss", "death of"]),
    ("loneliness", "Loneliness", "struggle", ["lonely", "loneliness", "alone", "isolated"]),
    ("doubt", "Doubt", "struggle", ["doubt", "doubting", "questions about god"]),
    ("patience", "Patience & Waiting", "virtue", ["patience", "patient", "wait", "waiting"]),
    ("servanthood", "Servanthood", "virtue", ["serve", "servant", "service", "serving"]),
    ("leadership", "Leadership", "christian_life", ["leader", "leadership", "shepherd the flock"]),
    ("scripture", "Scripture & God's Word", "theology", ["scripture", "word of god", "the bible", "god's word"]),
    ("truth", "Truth", "theology", ["truth", "true", "lies"]),
    ("judgment", "Judgment", "eschatology", ["judgment", "judge", "judgement"]),
    ("second-coming", "Return of Christ", "eschatology", ["second coming", "return of christ", "he will come again"]),
    ("baptism", "Baptism", "practice", ["baptism", "baptized", "baptize"]),
    ("communion", "Communion / Lord's Supper", "practice", ["communion", "lord's supper", "bread and cup"]),
    ("fasting", "Fasting", "practice", ["fasting", "fast"]),
    ("guidance", "Guidance & God's Will", "christian_life", ["guidance", "god's will", "direction", "lead me", "path"]),
    ("comfort", "Comfort", "christian_life", ["comfort", "comforted", "consolation"]),
    ("strength", "Strength", "christian_life", ["strength", "strong", "strengthen", "weakness"]),
    ("reconciliation", "Reconciliation", "relationship", ["reconcile", "reconciliation", "restored relationship"]),
    ("freedom", "Freedom", "christian_life", ["freedom", "free", "set free", "slavery"]),
    ("anger", "Anger", "struggle", ["anger", "angry", "wrath", "rage"]),
    ("contentment", "Contentment", "virtue", ["contentment", "content", "satisfied"]),
    ("gods-love", "God's Love", "theology", ["god's love", "loved the world", "love of god", "god so loved"]),
    ("enemies", "Loving Enemies", "relationship", ["enemies", "enemy", "love your enemies"]),
    ("integrity", "Integrity & Honesty", "virtue", ["integrity", "honest", "honesty"]),
]

# (key, type, name, aliases, passages, link_passages, description)
ENTITIES: list[tuple[str, str, str, list[str], list[str], bool, str]] = [
    # ---- people
    ("jesus", "person", "Jesus", ["jesus", "christ", "jesus christ", "the messiah"], ["MAT.1.1-MAT.28.20", "MRK.1.1-MRK.16.20", "LUK.1.1-LUK.24.53", "JHN.1.1-JHN.21.25"], False, "Jesus of Nazareth; the Gospels narrate his life and teaching"),
    ("abraham", "person", "Abraham", ["abraham", "abram"], ["GEN.12.1-GEN.25.11"], False, "Patriarch called by God"),
    ("sarah", "person", "Sarah", ["sarah", "sarai"], ["GEN.17.15-GEN.23.20"], False, "Wife of Abraham"),
    ("isaac", "person", "Isaac", ["isaac"], ["GEN.21.1-GEN.35.29"], False, "Son of Abraham"),
    ("jacob", "person", "Jacob", ["jacob"], ["GEN.25.19-GEN.50.14"], False, "Patriarch, renamed Israel"),
    ("joseph-patriarch", "person", "Joseph (son of Jacob)", ["joseph and his brothers", "joseph's brothers", "joseph in egypt"], ["GEN.37.1-GEN.50.26"], False, "Son of Jacob who rose to power in Egypt"),
    ("moses", "person", "Moses", ["moses"], ["EXO.2.1-DEU.34.12"], False, "Prophet and leader of the Exodus"),
    ("aaron", "person", "Aaron", ["aaron"], ["EXO.4.14-NUM.20.29"], False, "Brother of Moses, high priest"),
    ("joshua", "person", "Joshua", ["joshua son of nun"], ["JOS.1.1-JOS.24.33"], False, "Successor of Moses"),
    ("gideon", "person", "Gideon", ["gideon"], ["JDG.6.1-JDG.8.35"], False, "Judge of Israel"),
    ("samson", "person", "Samson", ["samson"], ["JDG.13.1-JDG.16.31"], False, "Judge of Israel"),
    ("ruth", "person", "Ruth", ["ruth the moabite", "ruth and naomi"], ["RUT.1.1-RUT.4.22"], False, "Moabite woman of loyal love"),
    ("samuel", "person", "Samuel", ["the prophet samuel"], ["1SA.1.1-1SA.25.1"], False, "Prophet and judge"),
    ("david", "person", "David", ["king david"], ["1SA.16.1-1KI.2.11"], False, "King of Israel"),
    ("goliath", "person", "Goliath", ["goliath"], ["1SA.17.1-1SA.17.58"], False, "Philistine champion"),
    ("solomon", "person", "Solomon", ["king solomon", "solomon"], ["1KI.1.1-1KI.11.43"], False, "King of Israel, son of David"),
    ("elijah", "person", "Elijah", ["elijah"], ["1KI.17.1-2KI.2.11"], False, "Prophet"),
    ("elisha", "person", "Elisha", ["elisha"], ["1KI.19.19-2KI.13.21"], False, "Prophet, successor of Elijah"),
    ("isaiah", "person", "Isaiah", ["the prophet isaiah"], ["ISA.1.1-ISA.66.24"], False, "Prophet"),
    ("jeremiah", "person", "Jeremiah", ["the prophet jeremiah"], ["JER.1.1-JER.52.34"], False, "Prophet"),
    ("daniel", "person", "Daniel", ["the prophet daniel"], ["DAN.1.1-DAN.12.13"], False, "Prophet in Babylon"),
    ("jonah", "person", "Jonah", ["the prophet jonah"], ["JON.1.1-JON.4.11"], False, "Prophet sent to Nineveh"),
    ("esther", "person", "Esther", ["queen esther"], ["EST.1.1-EST.10.3"], False, "Queen of Persia"),
    ("nehemiah", "person", "Nehemiah", ["nehemiah"], ["NEH.1.1-NEH.13.31"], False, "Rebuilder of Jerusalem's walls"),
    ("job", "person", "Job", ["the story of job", "job's suffering", "patience of job"], ["JOB.1.1-JOB.42.17"], False, "Righteous sufferer"),
    ("noah", "person", "Noah", ["noah"], ["GEN.6.9-GEN.9.29"], False, "Builder of the ark"),
    ("adam-eve", "person", "Adam and Eve", ["adam and eve"], ["GEN.2.4-GEN.4.26"], False, "First humans"),
    ("mary-mother", "person", "Mary, mother of Jesus", ["virgin mary", "mary the mother of jesus", "mother of jesus"], ["LUK.1.26-LUK.2.52"], False, "Mother of Jesus"),
    ("john-baptist", "person", "John the Baptist", ["john the baptist"], ["MAT.3.1-MAT.3.17", "LUK.3.1-LUK.3.22"], False, "Prophet who baptised Jesus"),
    ("peter", "person", "Peter", ["simon peter", "the apostle peter", "peter"], ["MAT.16.13-MAT.16.20", "JHN.21.15-JHN.21.19"], False, "Apostle"),
    ("paul", "person", "Paul", ["the apostle paul", "paul", "saul of tarsus"], ["ACT.9.1-ACT.28.31"], False, "Apostle to the Gentiles"),
    ("john-apostle", "person", "John the Apostle", ["the apostle john", "the beloved disciple"], [], False, "Apostle"),
    ("thomas", "person", "Thomas", ["doubting thomas", "the apostle thomas"], ["JHN.20.24-JHN.20.29"], False, "Apostle"),
    ("mary-magdalene", "person", "Mary Magdalene", ["mary magdalene"], ["JHN.20.1-JHN.20.18"], False, "Witness of the resurrection"),
    ("martha", "person", "Martha", ["martha"], ["LUK.10.38-LUK.10.42", "JHN.11.1-JHN.11.44"], False, "Sister of Mary and Lazarus"),
    ("lazarus", "person", "Lazarus", ["lazarus"], ["JHN.11.1-JHN.12.11"], False, "Raised from the dead by Jesus"),
    ("nicodemus", "person", "Nicodemus", ["nicodemus"], ["JHN.3.1-JHN.3.21"], False, "Pharisee who visited Jesus at night"),
    ("zacchaeus", "person", "Zacchaeus", ["zacchaeus", "zaccheus"], ["LUK.19.1-LUK.19.10"], False, "Tax collector"),
    ("judas", "person", "Judas Iscariot", ["judas iscariot", "judas"], ["MAT.26.14-MAT.27.10"], False, "Betrayer of Jesus"),
    ("pilate", "person", "Pontius Pilate", ["pontius pilate", "pilate"], ["JHN.18.28-JHN.19.22"], False, "Roman governor"),
    ("stephen", "person", "Stephen", ["stephen the martyr"], ["ACT.6.8-ACT.7.60"], False, "First Christian martyr"),
    ("timothy", "person", "Timothy", ["timothy"], ["1TI.1.1-2TI.4.22"], False, "Paul's co-worker"),
    ("barnabas", "person", "Barnabas", ["barnabas"], ["ACT.4.36-ACT.15.39"], False, "Encourager and missionary"),
    ("pharaoh", "person", "Pharaoh", ["pharaoh"], ["EXO.5.1-EXO.14.31"], False, "King of Egypt"),
    ("naomi", "person", "Naomi", ["naomi"], ["RUT.1.1-RUT.4.22"], False, "Mother-in-law of Ruth"),
    # ---- places
    ("jerusalem", "place", "Jerusalem", ["jerusalem"], [], False, "City of David"),
    ("bethlehem", "place", "Bethlehem", ["bethlehem"], ["LUK.2.1-LUK.2.20"], False, "Birthplace of Jesus"),
    ("nazareth", "place", "Nazareth", ["nazareth"], [], False, "Hometown of Jesus"),
    ("galilee", "place", "Galilee", ["galilee", "sea of galilee"], [], False, "Region of Jesus' ministry"),
    ("egypt", "place", "Egypt", ["egypt"], [], False, "Land of Israel's slavery"),
    ("babylon", "place", "Babylon", ["babylon"], [], False, "Place of exile"),
    ("jordan", "place", "Jordan River", ["jordan river", "the jordan"], [], False, "River of Jesus' baptism"),
    ("sinai", "place", "Mount Sinai", ["mount sinai", "sinai"], ["EXO.19.1-EXO.20.21"], False, "Mountain of the covenant"),
    ("eden", "place", "Garden of Eden", ["garden of eden", "eden"], ["GEN.2.8-GEN.3.24"], False, "First garden"),
    ("golgotha", "place", "Golgotha (Calvary)", ["golgotha", "calvary"], ["JHN.19.16-JHN.19.30"], False, "Place of the crucifixion"),
    ("gethsemane", "place", "Gethsemane", ["gethsemane"], ["MAT.26.36-MAT.26.46"], False, "Garden where Jesus prayed"),
    ("rome", "place", "Rome", ["rome"], [], False, "Capital of the empire"),
    ("corinth", "place", "Corinth", ["corinth"], [], False, "Greek city with an early church"),
    ("ephesus", "place", "Ephesus", ["ephesus"], [], False, "City in Asia Minor"),
    ("damascus", "place", "Damascus", ["damascus", "road to damascus"], ["ACT.9.1-ACT.9.19"], False, "City of Paul's conversion"),
    ("nineveh", "place", "Nineveh", ["nineveh"], ["JON.3.1-JON.4.11"], False, "Assyrian capital"),
    ("red-sea", "place", "Red Sea", ["red sea"], ["EXO.14.1-EXO.15.21"], False, "Sea crossed in the Exodus"),
    ("canaan", "place", "Canaan", ["canaan", "promised land"], [], False, "The promised land"),
    # ---- events / named passages (link_passages=True => mention implies a contextual passage reference)
    ("creation-account", "event", "Creation", ["creation account", "creation story", "six days of creation"], ["GEN.1.1-GEN.2.3"], True, "God creates the heavens and the earth"),
    ("fall", "event", "The Fall", ["the fall of man", "fall of humanity", "forbidden fruit"], ["GEN.3.1-GEN.3.24"], True, "Humanity's first sin"),
    ("flood", "event", "Noah and the Flood", ["noah's ark", "noah and the ark", "the great flood", "noah and the flood"], ["GEN.6.9-GEN.9.17"], True, "The flood and God's covenant with Noah"),
    ("babel", "event", "Tower of Babel", ["tower of babel"], ["GEN.11.1-GEN.11.9"], True, "Languages confused at Babel"),
    ("binding-of-isaac", "event", "Abraham offers Isaac", ["binding of isaac", "abraham offering isaac", "abraham sacrificing isaac", "abraham was tested", "sacrifice of isaac", "offering up isaac", "abraham offered isaac"], ["GEN.22.1-GEN.22.19"], True, "Abraham's faith tested on Mount Moriah"),
    ("jacob-wrestles", "event", "Jacob wrestles with God", ["jacob wrestled", "jacob wrestling"], ["GEN.32.22-GEN.32.32"], True, "Jacob renamed Israel"),
    ("joseph-sold", "event", "Joseph sold into slavery", ["joseph was sold", "sold joseph into slavery", "joseph sold into slavery"], ["GEN.37.12-GEN.37.36"], True, "Joseph betrayed by his brothers"),
    ("joseph-forgives", "event", "Joseph forgives his brothers", ["joseph forgave his brothers", "joseph forgives his brothers", "you meant it for evil", "meant it for harm"], ["GEN.50.15-GEN.50.21"], True, "Joseph reassures his brothers"),
    ("burning-bush", "event", "The burning bush", ["burning bush"], ["EXO.3.1-EXO.3.22"], True, "God calls Moses"),
    ("passover", "event", "The first Passover", ["the first passover", "passover lamb"], ["EXO.12.1-EXO.12.51"], True, "Israel spared in Egypt"),
    ("red-sea-crossing", "event", "Crossing the Red Sea", ["parting of the red sea", "crossing the red sea", "crossed the red sea", "red sea parted"], ["EXO.14.1-EXO.14.31"], True, "Israel delivered from Egypt"),
    ("ten-commandments", "event", "The Ten Commandments", ["ten commandments"], ["EXO.20.1-EXO.20.17"], True, "The law given at Sinai"),
    ("golden-calf", "event", "The golden calf", ["golden calf"], ["EXO.32.1-EXO.32.35"], True, "Israel's idolatry at Sinai"),
    ("jericho", "event", "Fall of Jericho", ["walls of jericho", "battle of jericho", "fall of jericho"], ["JOS.6.1-JOS.6.27"], True, "Jericho's walls fall"),
    ("david-goliath", "event", "David and Goliath", ["david and goliath"], ["1SA.17.1-1SA.17.58"], True, "David defeats Goliath"),
    ("david-bathsheba", "event", "David and Bathsheba", ["david and bathsheba"], ["2SA.11.1-2SA.12.25"], True, "David's sin and Nathan's rebuke"),
    ("elijah-carmel", "event", "Elijah on Mount Carmel", ["mount carmel", "prophets of baal"], ["1KI.18.20-1KI.18.40"], True, "Fire from heaven"),
    ("still-small-voice", "event", "Elijah hears the still small voice", ["still small voice", "gentle whisper"], ["1KI.19.9-1KI.19.18"], True, "God speaks to Elijah"),
    ("fiery-furnace", "event", "The fiery furnace", ["fiery furnace", "shadrach, meshach", "shadrach meshach and abednego"], ["DAN.3.1-DAN.3.30"], True, "Three men delivered"),
    ("lions-den", "event", "Daniel in the lions' den", ["lions' den", "lions den", "den of lions"], ["DAN.6.1-DAN.6.28"], True, "Daniel delivered"),
    ("jonah-fish", "event", "Jonah and the great fish", ["jonah and the whale", "swallowed by a great fish", "belly of the fish", "jonah and the great fish"], ["JON.1.1-JON.2.10"], True, "Jonah's flight and rescue"),
    ("nativity", "event", "Birth of Jesus", ["birth of jesus", "the nativity", "christmas story", "born in bethlehem"], ["LUK.2.1-LUK.2.20"], True, "Jesus born in Bethlehem"),
    ("baptism-of-jesus", "event", "Baptism of Jesus", ["baptism of jesus", "jesus was baptized"], ["MAT.3.13-MAT.3.17"], True, "The Spirit descends"),
    ("temptation-of-jesus", "event", "Temptation of Jesus", ["temptation in the wilderness", "jesus was tempted", "temptation of jesus"], ["MAT.4.1-MAT.4.11"], True, "Jesus tempted in the wilderness"),
    ("sermon-on-the-mount", "event", "Sermon on the Mount", ["sermon on the mount"], ["MAT.5.1-MAT.7.27"], True, "Jesus' teaching on the mountain"),
    ("beatitudes", "event", "The Beatitudes", ["the beatitudes", "beatitudes"], ["MAT.5.1-MAT.5.12"], True, "Blessed are..."),
    ("lords-prayer", "event", "The Lord's Prayer", ["the lord's prayer", "lord's prayer", "lords prayer"], ["MAT.6.9-MAT.6.13"], True, "Jesus teaches his disciples to pray"),
    ("sower", "event", "Parable of the Sower", ["parable of the sower", "the sower"], ["MAT.13.1-MAT.13.23"], True, "Seed on different soils"),
    ("feeding-5000", "event", "Feeding of the five thousand", ["feeding of the five thousand", "feeding of the 5000", "five loaves and two fish", "loaves and fishes"], ["JHN.6.1-JHN.6.14"], True, "Jesus feeds a multitude"),
    ("walks-on-water", "event", "Jesus walks on water", ["walked on water", "walking on water", "walks on water", "peter walked on the water"], ["MAT.14.22-MAT.14.33"], True, "Jesus and Peter on the lake"),
    ("transfiguration", "event", "The Transfiguration", ["transfiguration"], ["MAT.17.1-MAT.17.13"], True, "Jesus transfigured"),
    ("good-samaritan", "event", "Parable of the Good Samaritan", ["good samaritan"], ["LUK.10.25-LUK.10.37"], True, "Who is my neighbour?"),
    ("mary-martha", "event", "Mary and Martha", ["mary and martha"], ["LUK.10.38-LUK.10.42"], True, "The better part"),
    ("lost-sheep", "event", "Parable of the Lost Sheep", ["parable of the lost sheep", "the lost sheep", "ninety-nine sheep"], ["LUK.15.1-LUK.15.7"], True, "Joy over one sinner who repents"),
    ("prodigal-son", "event", "Parable of the Prodigal Son", ["prodigal son", "the lost son", "parable of the prodigal"], ["LUK.15.11-LUK.15.32"], True, "The father's welcome"),
    ("zacchaeus-story", "event", "Zacchaeus meets Jesus", ["zacchaeus climbed", "zacchaeus climbing", "zacchaeus in the tree", "zacchaeus", "zaccheus"], ["LUK.19.1-LUK.19.10"], True, "Salvation comes to Zacchaeus"),
    ("nicodemus-night", "event", "Jesus and Nicodemus", ["born again", "you must be born again"], ["JHN.3.1-JHN.3.21"], True, "New birth"),
    ("woman-at-the-well", "event", "The woman at the well", ["woman at the well", "samaritan woman", "living water"], ["JHN.4.1-JHN.4.42"], True, "Living water"),
    ("raising-lazarus", "event", "Raising of Lazarus", ["raising of lazarus", "raised lazarus", "lazarus come out", "lazarus from the dead"], ["JHN.11.1-JHN.11.44"], True, "I am the resurrection"),
    ("triumphal-entry", "event", "Triumphal entry", ["triumphal entry", "palm sunday"], ["MAT.21.1-MAT.21.11"], True, "Jesus enters Jerusalem"),
    ("last-supper", "event", "The Last Supper", ["last supper"], ["LUK.22.7-LUK.22.38"], True, "Jesus' final meal with the disciples"),
    ("foot-washing", "event", "Jesus washes the disciples' feet", ["washed the disciples' feet", "washing the disciples' feet", "washed their feet"], ["JHN.13.1-JHN.13.17"], True, "Servant leadership"),
    ("gethsemane-prayer", "event", "Prayer in Gethsemane", ["garden of gethsemane", "not my will but yours"], ["MAT.26.36-MAT.26.46"], True, "Jesus prays before his arrest"),
    ("peter-denial", "event", "Peter denies Jesus", ["peter denied jesus", "peter's denial", "denied him three times"], ["LUK.22.54-LUK.22.62"], True, "Peter's denial"),
    ("crucifixion", "event", "The Crucifixion", ["the crucifixion", "jesus was crucified", "died on the cross"], ["LUK.23.26-LUK.23.49"], True, "Jesus dies on the cross"),
    ("resurrection-event", "event", "The Resurrection", ["empty tomb", "he is risen", "jesus rose from the dead"], ["MAT.28.1-MAT.28.10", "JHN.20.1-JHN.20.18"], True, "Jesus is raised"),
    ("emmaus", "event", "Road to Emmaus", ["road to emmaus", "emmaus"], ["LUK.24.13-LUK.24.35"], True, "The risen Jesus explains the Scriptures"),
    ("peter-restored", "event", "Peter restored", ["do you love me", "feed my sheep", "peter was restored"], ["JHN.21.15-JHN.21.19"], True, "Jesus restores Peter"),
    ("great-commission", "event", "The Great Commission", ["great commission", "go and make disciples", "make disciples of all nations"], ["MAT.28.16-MAT.28.20"], True, "Jesus sends his disciples"),
    ("pentecost", "event", "Pentecost", ["pentecost", "day of pentecost"], ["ACT.2.1-ACT.2.41"], True, "The Spirit is poured out"),
    ("pauls-conversion", "event", "Conversion of Paul", ["road to damascus", "paul's conversion", "conversion of saul", "saul's conversion"], ["ACT.9.1-ACT.9.19"], True, "Saul meets the risen Jesus"),
    ("love-chapter", "event", "The love chapter", ["love chapter"], ["1CO.13.1-1CO.13.13"], True, "Love is patient..."),
    ("fruit-of-the-spirit", "event", "Fruit of the Spirit", ["fruit of the spirit"], ["GAL.5.22-GAL.5.23"], True, "Love, joy, peace..."),
    ("armor-of-god", "event", "Armor of God", ["armor of god", "armour of god", "full armor"], ["EPH.6.10-EPH.6.20"], True, "Stand firm"),
    ("hall-of-faith", "event", "Hall of faith", ["hall of faith", "faith chapter"], ["HEB.11.1-HEB.11.40"], True, "Heroes of faith"),
    ("new-creation-rev", "event", "New heaven and new earth", ["new heaven and a new earth", "new heaven and new earth", "new jerusalem"], ["REV.21.1-REV.21.8"], True, "All things made new"),
    # ---- life situations
    ("ls-grief", "life_situation", "Grieving a loss", ["loss of a loved one", "grieving", "funeral", "passed away"], [], False, ""),
    ("ls-anxiety", "life_situation", "Struggling with anxiety", ["anxious", "anxiety", "panic", "overwhelmed"], [], False, ""),
    ("ls-illness", "life_situation", "Facing illness", ["diagnosis", "cancer", "hospital", "chronic illness", "sick"], [], False, ""),
    ("ls-job-loss", "life_situation", "Job loss or career change", ["lost my job", "laid off", "unemployed", "job loss"], [], False, ""),
    ("ls-finances", "life_situation", "Financial hardship", ["debt", "bills", "financial stress", "can't pay"], [], False, ""),
    ("ls-marriage", "life_situation", "Marriage struggles", ["marriage problems", "divorce", "struggling marriage"], [], False, ""),
    ("ls-parenting", "life_situation", "Parenting challenges", ["parenting", "raising children", "teenager"], [], False, ""),
    ("ls-loneliness", "life_situation", "Loneliness", ["lonely", "isolated", "no friends"], [], False, ""),
    ("ls-addiction", "life_situation", "Addiction and recovery", ["addiction", "recovery", "sobriety"], [], False, ""),
    ("ls-conflict", "life_situation", "Conflict and broken relationships", ["conflict", "argument", "falling out", "estranged"], [], False, ""),
    ("ls-betrayal", "life_situation", "Betrayal", ["betrayed", "betrayal", "hurt by someone"], [], False, ""),
    ("ls-depression", "life_situation", "Depression and despair", ["depression", "depressed", "despair", "hopeless"], [], False, ""),
    ("ls-decisions", "life_situation", "Making a big decision", ["big decision", "which path", "decide"], [], False, ""),
    ("ls-waiting", "life_situation", "Waiting on God", ["waiting on god", "unanswered prayer", "season of waiting"], [], False, ""),
    ("ls-failure", "life_situation", "Failure and shame", ["failure", "failed", "shame", "guilt"], [], False, ""),
    ("ls-persecution", "life_situation", "Persecution for faith", ["persecution", "persecuted", "mocked for my faith"], [], False, ""),
    ("ls-suffering", "life_situation", "When everything goes wrong", ["everything goes wrong", "hard season", "difficult season", "going through hell"], [], False, ""),
    ("ls-new-beginning", "life_situation", "New beginnings", ["new beginning", "fresh start", "starting over"], [], False, ""),
    # ---- questions
    ("q-suffering", "question", "Why does God allow suffering?", ["why does god allow suffering", "why do bad things happen", "where is god in suffering"], [], False, ""),
    ("q-forgive", "question", "How can I forgive someone who hurt me?", ["how can i forgive", "how do i forgive", "how many times should i forgive"], [], False, ""),
    ("q-faith", "question", "What is faith?", ["what is faith"], [], False, ""),
    ("q-pray", "question", "How should I pray?", ["how should i pray", "how do i pray", "teach us to pray"], [], False, ""),
    ("q-control", "question", "Is God in control?", ["is god in control", "does god have a plan"], [], False, ""),
    ("q-death", "question", "What happens after death?", ["what happens after death", "life after death"], [], False, ""),
    ("q-saved", "question", "How can I be saved?", ["how can i be saved", "what must i do to be saved"], [], False, ""),
    ("q-will", "question", "How do I know God's will?", ["god's will for my life", "how do i know god's will"], [], False, ""),
    ("q-anxiety", "question", "How do I deal with worry?", ["how do i stop worrying", "how to deal with anxiety"], [], False, ""),
    ("q-enemies", "question", "How do I love my enemies?", ["love my enemies", "love your enemies"], [], False, ""),
]
